os:
- osx

language: cpp

compiler:
- clang++

env:
# Default build. Release.
- BUILD_ARGS=""
#before_install:
#- sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
#- sudo apt-get update -qq
#- sudo apt-get install -qq qt5-qmake qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libsqlite3-dev libx11-xcb-dev libglu1-mesa-dev libxrender-dev qttools5-dev-tools

before_install:
- brew install qt5
- chmod u+x generate_paths_travis.sh
- bash generate_paths_travis.sh
- bash build_deps.sh no-pause
install: true
script:
- bash build.sh no-pause
