language: c
branches:
except:
gh-pages
compiler:
- gcc
- clang
before_install:
- sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
- sudo apt-get update -qq
- sudo apt-get install -qq qt5-qmake qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libsqlite3-dev libx11-xcb-dev libglu1-mesa-dev libxrender-dev
- sh generate_paths_travis.sh
- sh build_deps.sh
script:
- sh build.sh
