#----------------------------------------------------------------------------
#
# Platform Game Engine Project by Wohlstand, a free platform for making games of platform genre
# Copyright (c) 2014-2015 Vitaly Novichkov <admin@wohlnet.ru>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#----------------------------------------------------------------------------
# Travis-CI building configuration file for Mac OS X Operating system
#                       created 2015-11-26
#----------------------------------------------------------------------------

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "eZjlsg6iAuRaU2qiofJUOFT8qmomXTgy9IpfbuI4UOLQpz7bXq9CVCrCE2HhoPLEj08AjLvn60sBDJE3vX7TWVDYAS4/tNx2mcWbRjPSlI0uIIC1ehCKUFoPu8wH8eJZCrJUijyPBf7WbZ2uDCar+pgAbecv+Fi//jUk1i+W/Q0="

git:
  depth: 1

branches:
  only:
    - master

language: cpp

os:
  - osx
  - linux

osx_image: xcode7
dist: trusty

compiler:
  - clang++

before_script:
  - bash _common/travis-ci/before-script.sh

before_install:
  - bash _common/travis-ci/before-install.sh
  - bash _common/travis-ci/build_dependencies.sh

install: true

script:
  - bash _common/travis-ci/build.sh

after_success:
  - bash _common/travis-ci/deploy.sh
  - bash _common/travis-ci/upload.sh

addons:
  coverity_scan:
    project:
      name: "WohlSoft/PGE-Project"
      description: "PGE Project - a free and open source game engine to create games of platform genre"
    notification_email: admin@wohlnet.ru
    branch_pattern: master

