#----------------------------------------------------------------------------
#
# Platform Game Engine Project by Wohlstand, a free platform for making games of platform genre
# Copyright (c) 2014-2017 Vitaly Novichkov <admin@wohlnet.ru>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#--------------------------------------------------------------------------------
# AppVeyor CI building configuration file for Microsoft Windows Operating system
#                             created 2015-11-25
#--------------------------------------------------------------------------------

version: 0.4.0.3.{build}

# you can use {branch} name in version format too
# version: 1.0.{build}-{branch}

branches:
  only:  # whitelist
    - master

skip_tags: true

skip_commits:
    message: /Created.*\.(png|jpg|jpeg|bmp|gif)/       # Regex for matching commit message

# Operating system (build VM template)
os: unstable

# clone directory
clone_folder: C:\_Repos\PGE-Project
clone_depth:  3  # clone entire repository history if not defined
# Uncommend those two lines to enable RDP (which can be used to debug stuff and test built stuff)
# init:
# - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  - ps: new-item C:\temp-d -itemtype directory
  - ps: (new-object net.webclient).DownloadFile('http://wohlsoft.ru/docs/Software/QtBuilds/MinGW-w64-x86_64-7.1.0-posix-seh-rt_v5-rev0.7z', 'C:\temp-d\MinGW-w64-x86_64-7.1.0-posix-seh-rt_v5-rev0.7z');
  - ps: (new-object net.webclient).DownloadFile('http://wohlsoft.ru/docs/Software/QtBuilds/Qt-5.9.0-x64-shared-mingw-w64-posix-seh-7-1-0.7z', 'C:\temp-d\Qt-5.9.0-x64-shared-mingw-w64-posix-seh-7-1-0.7z');
  - ps: |
      Set-Alias sevenzip "C:\Program Files\7-Zip\7z.exe"
      sevenzip x C:\temp-d\MinGW-w64-x86_64-7.1.0-posix-seh-rt_v5-rev0.7z -oC:\MinGW-w64;
      sevenzip x C:\temp-d\Qt-5.9.0-x64-shared-mingw-w64-posix-seh-7-1-0.7z -oC:\Qt;
  - cmd: git submodule init
  - cmd: git submodule update
  - cmd: echo set QtDir=C:\Qt\5.9.0-x64\bin>> _paths.bat # Qt since 5.8 no more supports Windows XP
  - cmd: echo set MinGW=C:\mingw-w64\x86_64-7.1.0-posix-seh-rt_v5-rev0\mingw64\bin>> _paths.bat
  - cmd: echo set MINGWx64Dest=yes>> _paths.bat
  - cmd: echo set GitDir=C:\Program Files\Git\cmd>> _paths.bat
  - cmd: echo date +'%%%%Y-%%%%m-%%%%d %%%%H:%%%%M:%%%%S' > temp.sh
  - cmd: type temp.sh
  - cmd: "\"C:\\Program Files\\Git\\bin\\bash.exe\" temp.sh > build_date_dev_win64.txt"
  - cmd: type build_date_dev_win64.txt
  - cmd: del temp.sh

build_script:
  - build_deps.bat nopause
  - build.bat nopause # noengine nocalibrator nogifs2png nopng2gifs nolazyfixtool nomanager nomaintainer nomusicplayer
  - cd _Misc\dev_scripts\deploy\
  - deploy_windows_dynamic_x64.bat nopause
  - cd ..\..\..\

artifacts:
  - path: bin-w64\_packed\pge-project-dev-win64.zip
  - path: bin-w64\_packed\install-pge-common-dev-win64.zip
  - path: bin-w64\_packed\install-pge-editor-dev-win64.zip
  - path: bin-w64\_packed\install-pge-engine-dev-win64.zip #This archive has no built applications (engine disabled to don't excite building timeout)
  - path: bin-w64\_packed\install-pge-tools-dev-win64.zip  #This archive has no built applications (toosl are disabled to don't excite building timeout)
  - path: bin-w64\_packed\pge-maintainer-dev-win64.zip  #Standalone package of PGE Maintainer (work outside PGE)
  - path: bin-w64\_packed\pge-musplay-dev-win64.zip     #Standalone package of PGE MusPlay (work outside PGE)
  - path: build_date_dev_win64.txt

deploy:
  - provider: Environment
    name: WohlnetFTP

